---

- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true

- include_tasks: rng-tools.yml
  when:
    - (freeipa_install_rngtools | d(false))

- include_tasks: pam-mkhomedir-fix.yml
  when:
    - (freeipa_fix_mkhomedir | d(false))
    - ansible_distribution|string == 'Ubuntu'
    - ansible_distribution_major_version|int <= 16
